config/routes.rb
Rails.application.routes.draw do

  get 'access/logout'
  post 'access/create'
  get 'access/new'

  resources :teams do
    resources :users
  end

  root to: 'access#new'

  resources :members, only: [:index, :show, :edit, :update]

  resources :users do
    resources :performance_reviews
  end

  resources :admins

  resources :home

  resources  :questions

  resources :questionnaires do
    resources  :questions
  end

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id               :integer          not null, primary key
#  description      :text
#  title            :string(255)
#  max_rate         :integer
#  questionnaire_id :integer
#  created_at       :datetime
#  updated_at       :datetime
#

class Question < ActiveRecord::Base
  has_many :feedbacks
  belongs_to :questionnaire, dependent: :destroy

  before_create :set_questionnaire

  validates :max_rate, numericality: {less_than_or_equal_to: 10, greater_than_or_equal_to: 3, message: 'must be a number between 3 and 10'}
  validates :description, presence: {value: true, message: 'is required'}

  scope :sorted, lambda {order(:created_at)}

  def set_questionnaire
    if self.questionnaire_id.blank?
      self.questionnaire = Questionnaire.first
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  layout 'admin'

  before_action   :confirm_admin_access
  before_action   :find_question, only: [:destroy, :show, :edit, :update]

  def new
    @question = Question.new
  end


  def index
    if params[:questionnaire_id].present?
      @all = false
      @questions = Questionnaire.find(params[:questionnaire_id]).questions
    else
      @questions = Question.sorted
      @all = true
    end
    #@questions = Questionnaire.find(params[:questionnaire_id]).questions
  end

  def update
    if  @question.update(question_params)
      flash[:notice] = 'Question has been updated successfully'
      redirect_to action: :index
    else
      flash[:notice] = 'Unable to update question ensure no blank field'
      render :edit
    end
  end

  def show
  end

  def edit
  end

  def create
    @question = Question.create(question_params)
    if @question.save
      flash[:notice] = 'Question added successfully'
      redirect_to questionnaire_questions_path(questionnaire_id: params[:questionnaire_id])   #(@question)
    else
      #flash[:notice] = 'Unable to submit question, please fill all the filed'
      render 'new'
    end
  end

  def destroy
    @question = @question.destroy
    flash[:notice] = 'Question successfully removed'
    redirect_to action: :index
  end




  protected
    def question_params
      params.require(:question).permit(:description, :title, :max_rate)
    end

    def find_question
      @question = Question.find(params[:id])
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= error_messages_for(@question) %>
<div class="form-group">
  <label for="title">Title:</label>
  <input type="text" class="form-control" id="title" name="question[title]" placeholder="Question title" value="<%= f.title.blank? ? '': f.title%>">
</div>
<div class="form-group">
  <label for="question">Content:</label><br>
  <textarea class="form-control" id="description" rows="8" name="question[description]" placeholder="Description" ><%= f.description.blank? ? '': f.description %></textarea>
</div>
<div class="form-group">
  <label for="max_rate">Max rating:</label><br>
  <input type="text" class="form-control" id="max_rate" name="question[max_rate]" placeholder="Maximum rating" value="<%= f.max_rate.blank? ? '': f.max_rate%>">
</div>

app/views/questions/edit.html.erb
<% @page_title='Question - Edit' %>
<div class="container">
  <div class="panel">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div class="panel panel-info">
            <div class="panel-heading"><h4>Update titled <%= @question.title %></h4></div>
            <div class="panel-body">
            <%= form_for @question, url: question_path(@question)  do |f|%>
                <%= render partial: 'form', locals: {f: @question} %>
                <%= f.submit('Update question', class: 'btn btn-info')%>
								<%= link_to 'Cancel', questions_path, class: 'btn btn-warning pull-right' %>
						<% end %>
            </div>
          </div>
        </div>
      </div> <!--end column-->
    </div><!-- END ROW -->
		</div>
  </div>

app/views/questions/index.html.erb
<% @page_title = 'Questions' %>
<div class="container">
  <div class="panel-heading"><h3>Questions</h3></div>

	<div><%= link_to '<span class="glyphicon glyphicon-plus"></span> Add a New Question'.html_safe, { controller: 'questions', action: :new} , class: 'btn btn-info'%> </div>
		<br> <br>
	<table class="table table-bordered table-striped text-center">
		<tr>
			<th class="text-center"> Question</th>
			<th class="text-center">Maximum rating</th>
			<% if @all %>
				<td>Questionnaire</td>
			<% end %>
			<th colspan="3" class="text-center">Actions</th>
		</tr>
		<% @questions.each do |question| %>
		<tr>
			<td><%= question.title %></td>
			<td class="center"><%= question.max_rate %></td>
			<% if @all %>
				<td><%= question.questionnaire.title %></td>
			<% end %>
			<td class="action">
				<%= link_to('Show', question, class: 'btn btn-info') %></td>
			<td>
				<%= link_to('Edit', {:action => :edit, :id => question.id}, class: 'btn btn-info') %>
		</td>
		<td>
				<%= link_to('Delete', question_path(question),class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure'}) %>
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/questions/new.html.erb
<% @page_title = 'Question - New' %>

<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-info">
        <div class="panel-heading"><h4> Add a new question</h4></div>
        <div class="panel-body">
          <%= form_for @question, url: questions_path  do |f|%>
            <%= render partial: 'form', locals: {f: @question } %>
            <%= f.submit('Save question', class: 'btn btn-info')%>
						<%= link_to 'Cancel', questions_path, class: 'btn btn-warning pull-right' %>
          <% end %>
        </div>
      </div>
    </div> <!--end column-->
  </div> <!--end row-->
</div>

app/views/questions/show.html.erb
<% @page_title = 'Question - ' + (@question.title||'') %>
<div class="container-fluid" xmlns="http://www.w3.org/1999/html">
  <div class="row">
    <div class="col-md-5 col-md-offset-2">
      <div>
        <%= link_to 'Back to questions list', questions_path , class: 'btn btn-info' %>
      </div><br><br>
      <div class="panel panel-info">
        <div class="panel-heading"><h3>Question details</h3></div>
        <div class="panel-body">
          <table class="table">
            <tr>
              <td><strong>Summary:</strong></td>
              <td><%= @question.title %></td>
            </tr>
            <tr>
              <td><strong>Question:</strong></td>
              <td><%= @question.description %></td>
            </tr>
            <tr>
              <td><strong>Maximum rating:</strong></td>
              <td><%= @question.max_rate %></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>