config/routes.rb
Rails.application.routes.draw do

  get 'access/logout'
  post 'access/create'
  get 'access/new'

  resources :teams do
    resources :users
  end

  root to: 'access#new'

  resources :members, only: [:index, :show, :edit, :update]

  resources :users do
    resources :performance_reviews
  end

  resources :admins

  resources :home

  resources  :questions

  resources :questionnaires do
    resources  :questions
  end

end

app/views/admins/_admin_form.html.erb
<%= error_messages_for(@admin) %>
<div class="form-group">
  <%= f.label :first_name, class: 'form-control' %>
  <%= f.text_field :first_name , class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :last_name, class: 'form-control' %>
  <%= f.text_field :last_name , class: 'form-control'%>
      </div>
<div class="form-group">
  <%= f.label :email, class: 'form-control' %>
  <%= f.text_field :email , class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :password, class: 'form-control' %>
  <%= f.password_field :password , class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation, class: 'form-control' %>
  <%= f.password_field :password_confirmation , class: 'form-control' %>
</div>

app/views/admins/_form.html.erb
<%= error_messages_for(@admin) %>
<div class="form-group">
  <%= f.label :first_name %>
  <%= f.text_field :first_name , class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :last_name %>
  <%= f.text_field :last_name , class: 'form-control'%>
      </div>
<div class="form-group">
  <%= f.label :email%>
  <%= f.text_field :email , class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password , class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation , class: 'form-control' %>
</div>

app/views/admins/index.html.erb
<% @page_title='Admin dashboard' %>
<div class="container">
	<div class="panel panel-info">
		<div class="panel-heading"><h1>Admin dashboard</h1></div>
		<div class="panel-body">
			<div>
				<%= link_to 'Questionnaires', questionnaires_path, class: 'form-control btn btn-lg btn-info' %><br><br>
				<%= link_to 'Teams', teams_path, class: 'form-control btn btn-info btn-lg' %><br><br>
				<%= link_to 'Questions', questions_path, class: 'form-control btn btn-info btn-lg' %><br><br>
				<%= link_to 'Settings', edit_user_path(current_user), class: 'form-control btn btn-info btn-lg' %><br><br>
				<%= link_to 'Add a new admin', new_admin_path, class: 'form-control btn btn-info btn-lg' %><br><br>

			</div>
		</div>
	</div>
</div>

app/views/admins/new.html.erb
<% @page_title = 'Admin - New'%>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-2">
			<div class="panel panel-warning">
				<div class="panel-heading"><h3>Register a new admin</h3></div>
				<div class="panel-body">
					<%= form_for @admin , url: {action: 'create'} do |f|%>
						<%= render partial: 'admins/form', locals: {f: f }%>
						<%= f.submit 'Save admin', class: 'btn btn-warning' %>
						<%= link_to 'Cancel', is_admin? ? admins_path : members_path, class: 'btn btn-warning pull-right' %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>