config/routes.rb
Rails.application.routes.draw do

  get 'access/logout'
  post 'access/create'
  get 'access/new'

  resources :teams do
    resources :users
  end

  root to: 'access#new'

  resources :members, only: [:index, :show, :edit, :update]

  resources :users do
    resources :performance_reviews
  end

  resources :admins

  resources :home

  resources  :questions

  resources :questionnaires do
    resources  :questions
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  team_id         :integer
#  first_name      :string(50)
#  last_name       :string(100)
#  email           :string(255)
#  description     :text
#  password_digest :string(255)
#  type            :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base

  has_many  :performance_reviews
  belongs_to :team
  has_secure_password

  EMAIL_REGEX = /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: {with: EMAIL_REGEX, allow_blank: true}
  validates :password, presence: true, length: {in: 3..15, allow_blank: true}
  validates :password_confirmation, presence: true, on: :create, if: proc { |x| x.password.present? }

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def is_type?(type)
    self[:type]==type
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #refactor for actions that requires an object from it's id

  layout 'admin'

  before_action :logged_in?
  before_action :find_user, only: [:edit, :show, :update, :destroy]

  #layout setLayout

  def index
    @users = User.where(team_id: params[:team_id])
    render :index
  end

  def new
    @user = User.new
  end

  def update
    #saved =  @user.update(user_params)

    if @user.update(user_params)
      flash[:notice] = 'Update was successfully.'
      if is_admin?
        render :action => :show, id: @user.id
      else
        redirect_to members_path
      end
    else
      #flash[:error] = 'Attempt to update user details failed, try again'
      render :edit
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:notice] = "User #{@user.full_name} has been successfully added"
      render :action => :show, id: @user.id
    else
      #flash[:notice] = 'Attempt to add a new user failed, try again'
      render :new
    end
  end

  def destroy
    @user  = @user.destroy
    flash[:notice] = "User #{@user.full_name} has been successfully added"
    redirect_to action: :index
  end

  def show
  end

  def review
    @feedbacks = load_feedback(params[:id])
    @questions = Question.all
    render 'members/show'
  end

  def edit
    unless is_admin?
      render :layout => 'member'
    end
  end

  def find_user
    @user = User.find(params[:id])
    @user ||= Admin.find(params[:id])
  end

  private
  def user_params
    if params[:user].present?
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    else
      params.require(:admin).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= error_messages_for(@user) %>
<div class="form-group">
	<% # f.label :first_name %>
	<label>First name: </label>
	<%= f.text_field :first_name , class: 'form-control' %>
</div>
<div class="form-group">
	<% # f.label :last_name %>
	<label>Last name: </label>
	<%= f.text_field :last_name , class: 'form-control'%>
</div>
<div class="form-group">
	<%# f.label :email%>
	<label>Email: </label>
	<%= f.text_field :email , class: 'form-control' %>
</div>
<div class="form-group">
	<label>Password: </label>
	<% #f.label :password %>
	<%= f.password_field :password , class: 'form-control' %>
</div>
<div class="form-group">
	<label>Password confirmation: </label>
	<% # f.label :password_confirmation %>
	<%= f.password_field :password_confirmation , class: 'form-control' %>
</div>

app/views/users/_user_form.html.erb
<div class="form-group">
  <label for="position">First Name:</label>
  <input type="text" class="form-control" id="first_name" name="user[first_name]" placeholder="Enter user's first name " value="<%= user.first_name %>">
</div>
<div class="form-group">
  <label for="last_name">Last Name</label>
  <input type="text" class="form-control" id="summary" name="user[last_name]" placeholder="Enter user's last name" value="<%= user.last_name %>">
</div>
<div class="form-group">
  <label for="email">Email:</label><br>
  <input type="email" class="form-control" id="email" name="user[email]" placeholder="Enter your email" value="<%= user.email%>">
</div>
<div class="form-group">
  <label for="completed">Confirmation status:</label> &nbsp;
  <input type="checkbox"  id="completed" name="user[completed]" value="<%= user.completed? ? 1:0 %>">
</div>

app/views/users/edit.html.erb
<% @page_title='User - Edit' %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-2">
      <div class="panel panel-<%= them%>">
        <div class="panel-heading"><h4>Update user details</h4></div>
        <div class="panel-body">
          <%= form_for @user, url: user_path(@user)  do |f|%>
						<p class="alert alert-warning">If you are not changing your password, just re-enter the old one twice</p>
						<%= render partial: 'users/form', locals: {f: f} %>
						<%= f.submit class: "btn btn-#{them} pull-left" %>
						<%= link_to 'Cancel', is_admin? ? users_path : members_path, class: 'btn btn-warning pull-right' %>
				<% end %>
        </div>
      </div>
    </div> <!--end column-->
  </div> <!--end row-->
</div>

app/views/users/index.html.erb
<% @page_title='Users' %>
<div class=" container">

  <div class="row">
    <div class="col-md-10 col-md-offset-1">
			<% if @users.count==0 %>
				<div class="alert alert-info">No user in the db </div>
			<% else %>


      <div class="panel panel-info">
        <div class="panel-heading"><h3>List of users</h3></div>
      <div class="panel-body">
        <div>
          <%= pluralize(@users.count, 'user') +' found'%>
        </div>
      <table class="table table-bordered table-striped text-center">
        <tr>
          <th class="text-center">Name </th>
          <th colspan="4" class="text-center">Actions</th>
        </tr>
        <% @users.each do |user| %>
        <tr>
					<td class="text-left"><%= user.full_name.capitalize %></td>
					<td><%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_user_path(user), class: 'btn btn-info' %></td>
					<td>
						<%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe , user_path(user), class: 'btn btn-danger',method: :delete, data: {confirm: 'Are you sure?'} %></td>
					<td>
						<%= link_to 'Review', new_user_performance_review_path(user), class: 'btn btn-info' %>
					</td>
					<td>
						<%= link_to 'Feed backs', member_path(user.id), class: 'btn btn-info' %>
					</td>
        </tr>
        <% end %>
      </table>

				<% if is_admin? %>
					<div class="row">
						<div class="col-md-1">
							<div><%= link_to 'Add A new User', new_user_path, class: 'btn btn-info' %></div>
						</div>
					</div>
				<% end %>
        </div>
      </div>
			<% end %>
    </div>

    <div class="col-md-2">

    </div>
  </div>


</div>

app/views/users/new.html.erb
<% @page_title='User - New' %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-info">
        <div class="panel-heading"><h4>Add a new user</h4></div>
        <div class="panel-body">
          <%= form_for @user, url: users_path  do |f| %>
						<%= render partial: 'users/form', locals: {f: f} %>
						<div>
							<%= f.submit('Add user', class: 'btn btn-info pull-left')%>
							<%= link_to 'Cancel', is_admin? ? users_path : members_path, class: 'btn btn-warning pull-right' %>
						</div>
          <% end %>
        </div>
      </div>
    </div> <!--end column-->
  </div> <!--end row-->
</div>

app/views/users/show.html.erb
<% @page_title='User details' %>
<div class="container-fluid">
  <br>
    <div class="row">
      <div class="col-md-6 col-md-offset-2">
				<p>
					<%= link_to ' Back to users list', users_path , class: 'btn btn-info' %>
				</p>
        <div class="panel panel-info">
          <div class="panel-heading"><h3>Details for <%= @user.first_name.capitalize %></h3></div>
          <div class="panel-body">
            <table class="table">
              <tr>
                <td><strong>Full name:</strong></td>
                <td><%= @user.full_name %></td>
              </tr>
              <tr>
                <td><strong>Email:</strong></td>
                <td><%= @user.email %></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
</div>