config/routes.rb
Rails.application.routes.draw do

  get 'access/logout'
  post 'access/create'
  get 'access/new'

  resources :teams do
    resources :users
  end

  root to: 'access#new'

  resources :members, only: [:index, :show, :edit, :update]

  resources :users do
    resources :performance_reviews
  end

  resources :admins

  resources :home

  resources  :questions

  resources :questionnaires do
    resources  :questions
  end

end

app/controllers/performance_reviews_controller.rb
class PerformanceReviewsController < ApplicationController

  before_action :logged_in?
  before_action :is_admin?, only: [:edit, :update]
  layout 'admin'
  def index
    @user = User.find(params[:user_id])
    render 'index'
  end

  def new
    @user = User.find(params[:user_id])#params[:user_id])
    @performance_review = PerformanceReview.new
    Question.all.each do |question|
      @performance_review.feedbacks.build(question_id: question.id)
    end
    unless is_admin?
      render layout: 'member'
    end
    #render :new
  end

  def create
    #raise review_params.to_yaml
    # instantiate a new record
    @performance_review = PerformanceReview.new(review_params)
    @performance_review.reviewer_id = current_user.id
    @performance_review.reviewee_id = params[:user_id]

    @team = @performance_review.reviewee.team

    #attempt to save if
    if @performance_review.save
      flash[:notice] = 'Successfully saved PR'
      @users = User.all
      if is_admin?
        redirect_to team_users_path(@team)
      else
        redirect_to members_path
      end
    else
      #raise review_params.to_yaml
      #Will only fail due to validations, so ..
      flash[:error] = 'You must complete all filed before submitting your review'
        render

    end
  end

  def show
    @performance_review = PerformanceReview.find(params[:id])
    unless is_admin?
      render layout: 'member'
    end
  end



  def edit
    @user = User.find(params[:user_id])
    @performance_review = PerformanceReview.find(params[:id])
    render :'edit'
  end

  def update
  end


  def review_params
    params.require(:performance_review).permit(feedbacks_attributes: [:rating, :comment, :question_id])
  end
end

app/helpers/performance_reviews_helper.rb
module PerformanceReviewsHelper
end

app/views/performance_reviews/_comment_field.html.erb
<div class="form-group">
  <%= f.label :comment, 'Comment:'%><br>
  <%= f.text_area :comment, rows: 3, placeholder: 'Add your comment here' , class: 'form-control' %>
</div>

app/views/performance_reviews/_feedback_field.html.erb
<strong>Question:</strong>
<p><h5><%= f.object.question.description %></h5></p>
<%= f.hidden_field :question_id, value: f.object.question.id %>
<%= render partial: 'comment_field' , locals: {f: f}%>
<%= render partial: 'radio_buttons', locals: {f: f} %>
<hr>

app/views/performance_reviews/_form.html.erb
<%= error_messages_for(@performance_review) %>

<%= f.fields_for :feedbacks do |builder| %>
    <%= render partial: 'feedback_field',  locals: { f: builder} %>
<% end %><br><br>

app/views/performance_reviews/_radio_buttons.html.erb
<div class="form-group">
  <%(1...(f.object.question.max_rate + 1)).each do |i| %>
    <%= f.radio_button('rating' ,i) %>
    <%= f.label :i, i.to_s %>
  <% end %>
</div>

app/views/performance_reviews/edit.html.erb
<% @page_title='Edit' %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <p><%= link_to 'Back to members\' list', users_path, class: 'btn btn-info' %> </p>
      <div class="panel panel-info">
        <div class="panel-heading"><h3>Editing review of :<%=  %> </h3></div>
        <div class="panel-body">
					<%= form_for @performance_review, url: {action: :update} do |f| %>
						<%= render partial: 'form', locals: {f: f} %>
						<%= f.submit("Update review of #{current_user.full_name}", class: 'btn btn-info') %>
					<% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/performance_reviews/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-2">
      <div class="panel panel-primary">
        <div class="panel-heading"><h4>Logged in as <%= session[:username] %></h4></div>
        <div class="panel-body">
          <table class="table table-bordered table-striped">
            <tr>
              <th>Team Member</th>
              <th>View PR</th>
            </tr>
            <% User.all.each do |user|%>
            <tr>
              <td>
                <%= user.full_name %>
              </td>
              <td>
                <%= link_to 'Edit', new_user_performance_review_path(user.id) %>
              </td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/performance_reviews/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-1">
      <p><%= link_to 'Back to members\' list', is_admin? ? users_path : members_path, class: "btn btn-#{them}" %> </p>
      <div class="panel panel-<%= them%>">
        <div class="panel-heading"><h3>Reviewing <%= @user.full_name %> </h3></div>
				<div class="panel-body">
        <%= form_for @performance_review, url: user_performance_reviews_path do |f| %>
					<%= render partial: 'form', locals: {f: f} %>
					<%= f.submit("Submit Performance review for #{@user.full_name}", class: "btn btn-#{them} pull-left") %>
					<%= link_to 'Cancel', is_admin? ? users_path : members_path, class: 'btn btn-warning pull-right'%>
        <% end %>
				</div>
      </div>
    </div>
  </div>
</div>

app/views/performance_reviews/show.html.erb
<% @page_title='Review details' %>
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-<%= them %>">
				<div class="panel-heading"><h3>Review of <%= @performance_review.reviewee.full_name %></h3></div>
				<div class="panel-body">
					<% @performance_review.feedbacks.each do |x| %>
					<div class="panel panel-<%= them%>">
						<div class="panel-body">
							<strong>Question: </strong><%= x.question.description %><br>
							<p><strong>Comment: </strong><%= x.comment %></p>
						</div>
						<div class="panel-footer">
							Rating: <%= x.rating %>
						</div>
					</div>
					<% end %>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/performance_reviews/update.html.erb
<h1>PerformanceReviews#update</h1>
<p>Find me in app/views/performance_reviews/update.html.erb</p>